version: "3.3"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: timostroehlein/dhbw-bigdata-mtg-frontend
    command: npm run start
    volumes:
      - type: bind
        source: ./frontend
        target: /usr/src/app/
    environment:
      MONGO_INITDB_USERNAME: dev
      MONGO_INITDB_PASSWORD: dev
      MONGO_INITDB_DATABASE: mtg
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
    ports:
      - "3030:3000"
    networks:
      bigdatanet:

  hadoop:
    container_name: hadoop
    image: marcelmittelstaedt/spark_base:latest
    ports:
     - "8088:8088"
     - "9870:9870"
     - "9864:9864"
     - "10000:10000"
     - "8032:8032"
     - "8030:8030"
     - "8031:8031"
     - "9000:9000"
     - "8888:8888"
    volumes:
    - type: bind
      source: ./airflow/notebooks
      target: /home/hadoop/airflow/notebooks/
    networks:
      bigdatanet:

  airflow:
    container_name: airflow
    build: ./airflow
    image: timostroehlein/airflow:latest
    ports:
     - "8080:8080"
    volumes:
     - type: bind
       source: ./airflow/dags
       target: /home/airflow/airflow/dags/
     - type: bind
       source: ./airflow/python
       target: /home/airflow/airflow/python/
    networks:
      bigdatanet:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes: 
      - mongo:/data/mongodb
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INIT_DATABASE}
    networks:
      bigdatanet:

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGO_INIT_DATABASE}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    networks:
      bigdatanet:

networks:
  bigdatanet:

volumes:
  mongo:
